### ISSUE TITLE
modal_share_karma doesn't display on click

### ISSUE THREAD

**Issue by sethwoodworth** [FinalsClub/djKarma#32]
http://twitter.github.com/bootstrap/javascript.html#modals

The upload modal works, but share does not, nor does it work (for me) in the static profile.html design file from lingbo

**Comment by bnauheimer** [comment]
Who's issue is this to fix?

**Comment by lingboli** [comment]
I fixed this at the last meeting in the static version - it was just missing to closing </div> tags.

**Comment by sethwoodworth** [comment]
The issue remains.  Lingbo fixed a similar issue in the static templates where malformed html is breaking the modal dialog, but our html layout in the application is different at this point, so the change doesn't carry over.

I'll take this issue.

**Comment by sethwoodworth** [comment]
Pushed a fix, I will push it to beta tomorrow. commit b2c59deb
